aylist("Maand");
    // u.insertSongPlaylist("Husn");
    // u.insertSongPlaylist("Baarishein");
    // u.insertSongPlaylist("Paro");
    // u.insertSongPlaylist("Mann Mera");
    // u.insertSongPlaylist("Hero");
    // u.disp();
    // u.deleteSongFromPlaylist("Maand", u.root);
    // u.deleteSongFromPlaylist("herr",u.root);
    // u.disp();